"""The determinism recipe, asserted one variable at a time.

⚠️ Why the isolation matters. There are TWO independent sources of
non-determinism here, and during the spike that fact produced two wrong
conclusions in a row:

  1. `try(AlphaSimR::setNThreads(1), silent=TRUE)` was used to "rule out" OpenMP.
     Those functions DO NOT EXIST in AlphaSimR 2.1.0, so the pin silently no-opped
     and the discriminator discriminated nothing.
  2. `OMP_NUM_THREADS=1` was then tested correctly, but with founders generated by
     `runMacs` — whose own irreproducibility masked the OpenMP effect completely.
     "OpenMP ruled out" was recorded on the strength of that. It was wrong.

Only after fixing founders did the OpenMP signal become visible. So every test
below varies exactly ONE thing.
"""

import os
import subprocess
import sys

PROBE = """
import os, sys
sys.path.insert(0, {src!r})
os.environ.setdefault("R_LIBS_USER", os.path.expanduser("~/R/library"))
from breedsim_mcp.founding import found_population
from breedsim_mcp.replication import run_program
from breedsim_mcp.session import SessionStore

store = SessionStore()
s = found_population(store, generator={gen!r}, seed=1, n_ind=40, n_chr=4,
                     seg_sites=40, n_qtl_per_chr=5, h2=0.4)
out = run_program(store, s.session_id, cycles=2, replicates=5, base_seed=77)
print("HASH", s.founder_hash)
print("GAIN", round(out["cycles"][-1]["genetic_gain"]["mean"], 8))
"""


def _probe(generator: str, omp: str | None) -> tuple[str, str]:
    src = os.path.join(os.path.dirname(os.path.dirname(__file__)), "src")
    env = dict(os.environ)
    env.pop("OMP_NUM_THREADS", None)
    if omp is not None:
        env["OMP_NUM_THREADS"] = omp
    r = subprocess.run(
        [sys.executable, "-c", PROBE.format(src=src, gen=generator)],
        capture_output=True,
        text=True,
        env=env,
        timeout=900,
        check=False,
    )
    assert r.returncode == 0, r.stderr[-2000:]
    lines = dict(line.split(" ", 1) for line in r.stdout.strip().splitlines())
    return lines["HASH"], lines["GAIN"]


def test_the_full_recipe_reproduces_exactly():
    """quickHaplo founders + pinned threads + fixed seeds → identical results."""
    a = _probe("quickHaplo", omp="1")
    b = _probe("quickHaplo", omp="1")
    assert a == b, f"the documented recipe must reproduce: {a} vs {b}"


def test_within_one_session_runmacs_does_not_repeat_but_quickhaplo_does():
    """The failure mode that matters for a LONG-LIVED server process.

    Subtler than "runMacs ignores set.seed": MaCS's RNG is seeded once per R
    session and advances across calls, so the same call SEQUENCE reproduces in a
    fresh process while a REPEAT call inside one session does not. This server is
    a long-lived process, so the repeat case is the one users hit.
    """
    src = os.path.join(os.path.dirname(os.path.dirname(__file__)), "src")
    probe = """
import os, sys
sys.path.insert(0, {src!r})
os.environ.setdefault("R_LIBS_USER", os.path.expanduser("~/R/library"))
from breedsim_mcp.founding import found_population
from breedsim_mcp.session import SessionStore
store = SessionStore()
kw = dict(seed=1, n_ind=20, n_chr=2, seg_sites=20, n_qtl_per_chr=3, h2=0.4)
a = found_population(store, generator={gen!r}, **kw)
b = found_population(store, generator={gen!r}, **kw)
print("SAME", a.founder_hash == b.founder_hash)
""".format(src=src, gen="{gen}")

    def two_calls(generator: str) -> bool:
        env = dict(os.environ)
        env["OMP_NUM_THREADS"] = "1"
        r = subprocess.run(
            [sys.executable, "-c", probe.format(gen=generator)],
            capture_output=True,
            text=True,
            env=env,
            timeout=900,
            check=False,
        )
        assert r.returncode == 0, r.stderr[-2000:]
        return "SAME True" in r.stdout

    assert two_calls("runMacs") is False, (
        "two seeded runMacs calls in ONE session are expected to differ; if this "
        "ever passes, re-derive the reproducible flag before trusting it"
    )
    # Positive control in the same test: swap ONLY the generator.
    assert two_calls("quickHaplo") is True


def test_varying_only_the_thread_count_breaks_reproducibility():
    """Founders stay fixed (quickHaplo); ONLY OMP_NUM_THREADS changes.

    This is the assertion that was impossible to see while runMacs was in play.
    """
    pinned_a = _probe("quickHaplo", omp="1")
    pinned_b = _probe("quickHaplo", omp="1")
    assert pinned_a == pinned_b, "pinned must be stable before testing unpinned"

    unpinned_a = _probe("quickHaplo", omp="4")
    unpinned_b = _probe("quickHaplo", omp="4")
    # Founders are generated by R's RNG and stay identical; the GAIN is what the
    # threading perturbs, so assert on that specifically.
    assert unpinned_a[0] == unpinned_b[0], "quickHaplo founders should still match"
    assert unpinned_a[1] != unpinned_b[1], (
        "multi-threaded selection is expected to vary run to run; if this ever "
        "passes, re-measure before claiming determinism is free"
    )
